version: '3.7'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/var/www/employee-roll
      - ../node_modules:/var/www/employee-roll/node_modules
      - ../package.json:/var/www/employee-roll/package.json
      - ../package-lock.json:/var/www/employee-roll/package-lock.json
    environment:
      - NODE_ENV=development